--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(8)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(1044.5000, 798.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentX(0.4976)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2859)
layout:setPercentHeight(0.3757)
layout:setSize({width = 600.0000, height = 600.0000})
layout:setLeftMargin(744.5000)
layout:setRightMargin(754.5000)
layout:setTopMargin(498.5000)
layout:setBottomMargin(498.5000)
Scene:addChild(Panel_1)

--Create Map_1
local Map_1 = cc.TMXTiledMap:create("42x42map.tmx")
Map_1:setName("Map_1")
Map_1:setTag(5)
Map_1:setCascadeColorEnabled(true)
Map_1:setCascadeOpacityEnabled(true)
Map_1:setPosition(-497.1778, -261.1928)
Map_1:setScaleX(0.5000)
Map_1:setScaleY(0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Map_1)
layout:setPositionPercentX(-0.8286)
layout:setPositionPercentY(-0.4353)
layout:setPercentWidth(5.3200)
layout:setPercentHeight(3.9900)
layout:setSize({width = 3192.0000, height = 2394.0000})
layout:setLeftMargin(-497.1778)
layout:setRightMargin(-2094.8220)
layout:setTopMargin(-1532.8070)
layout:setBottomMargin(-261.1928)
Panel_1:addChild(Map_1)

--Create Sprite_1
local Sprite_1 = cc.Sprite:create("1_0000_Layer-3.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setTag(7)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setPosition(527.2890, 1215.6470)
Sprite_1:setScaleX(0.9996)
Sprite_1:setScaleY(0.9996)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentX(0.2512)
layout:setPositionPercentY(0.7612)
layout:setPercentWidth(0.5026)
layout:setPercentHeight(0.4778)
layout:setSize({width = 1055.0000, height = 763.0000})
layout:setLeftMargin(-0.2110)
layout:setRightMargin(1044.2110)
layout:setTopMargin(-0.1475)
layout:setBottomMargin(834.1475)
Sprite_1:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_1)

--Create Sprite_2
local Sprite_2 = cc.Sprite:create("1_0001_Layer-1.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(8)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(527.2890, 418.8324)
Sprite_2:setScaleX(0.9996)
Sprite_2:setScaleY(0.9996)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(0.2512)
layout:setPositionPercentY(0.2623)
layout:setPercentWidth(0.5026)
layout:setPercentHeight(0.5247)
layout:setSize({width = 1055.0000, height = 838.0000})
layout:setVerticalEdge(1)
layout:setLeftMargin(-0.2110)
layout:setRightMargin(1044.2110)
layout:setTopMargin(759.1676)
layout:setBottomMargin(-0.1676)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_2)

--Create Sprite_3
local Sprite_3 = cc.Sprite:create("1_0002_Layer-4.png")
Sprite_3:setName("Sprite_3")
Sprite_3:setTag(9)
Sprite_3:setCascadeColorEnabled(true)
Sprite_3:setCascadeOpacityEnabled(true)
Sprite_3:setPosition(1575.7910, 1216.1470)
Sprite_3:setScaleX(0.9996)
Sprite_3:setScaleY(0.9996)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_3)
layout:setPositionPercentX(0.7507)
layout:setPositionPercentY(0.7615)
layout:setPercentWidth(0.4979)
layout:setPercentHeight(0.4784)
layout:setSize({width = 1045.0000, height = 764.0000})
layout:setLeftMargin(1053.2910)
layout:setRightMargin(0.7090)
layout:setTopMargin(-1.1472)
layout:setBottomMargin(834.1472)
Sprite_3:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_3)

--Create Sprite_4
local Sprite_4 = cc.Sprite:create("1_0003_Layer-2.png")
Sprite_4:setName("Sprite_4")
Sprite_4:setTag(10)
Sprite_4:setCascadeColorEnabled(true)
Sprite_4:setCascadeOpacityEnabled(true)
Sprite_4:setPosition(1575.7910, 417.8328)
Sprite_4:setScaleX(0.9996)
Sprite_4:setScaleY(0.9996)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_4)
layout:setPositionPercentX(0.7507)
layout:setPositionPercentY(0.2616)
layout:setPercentWidth(0.4979)
layout:setPercentHeight(0.5235)
layout:setSize({width = 1045.0000, height = 836.0000})
layout:setLeftMargin(1053.2910)
layout:setRightMargin(0.7090)
layout:setTopMargin(761.1672)
layout:setBottomMargin(-0.1672)
Sprite_4:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Sprite_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

