var LOBBY_CFG = LOBBY_CFG || {};

LOBBY_CFG.ATTACK_X = 70;
LOBBY_CFG.ATTACK_Y = 60;

LOBBY_CFG.GUILD_X = 50;
LOBBY_CFG.GUILD_Y = 140;

LOBBY_CFG.GUILD_FIGHT_X = 50;
LOBBY_CFG.GUILD_FIGHT_Y = 200;

// shop
LOBBY_CFG.SHOP_X = 1000;
LOBBY_CFG.SHOP_Y = 60;

// setting
LOBBY_CFG.SETTING_X = 1020;
LOBBY_CFG.SETTING_Y = 140;

// letter
LOBBY_CFG.LETTER_X = 1020;
LOBBY_CFG.LETTER_Y = 200;

// friends
LOBBY_CFG.FRIEND_X = 920;
LOBBY_CFG.FRIEND_Y = 45;
