var LOGIN_CONFIG = LOGIN_CONFIG || {};

// background
LOGIN_CONFIG.SCALE_BACKGROUND_X = 1.5;
LOGIN_CONFIG.SCALE_BACKGROUND_Y = 1.5;

// logo
LOGIN_CONFIG.LOGO_X = 70;
LOGIN_CONFIG.LOGO_Y = 580;

// username box
LOGIN_CONFIG.LOGIN_BOX_WIDTH = 250;
LOGIN_CONFIG.LOGIN_BOX_HEIGHT = 40;
LOGIN_CONFIG.LOGIN_BOX_X = 500;
LOGIN_CONFIG.LOGIN_BOX_Y = 200;

// ok button
LOGIN_CONFIG.OK_BUTTON_WIDTH = 70;
LOGIN_CONFIG.OK_BUTTON_HEIGHT = 35;
LOGIN_CONFIG.OK_BUTTON_X = 700;
LOGIN_CONFIG.OK_BUTTON_Y = 200;

// loading
LOGIN_CONFIG.LOADING_X = 560;
LOGIN_CONFIG.LOADING_Y = 100;

